# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Old French spellchecker"
fro = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Old French, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
fro = "TRANSLATE: A spellchecker for Old French, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.fro"

[windows]
system_product_code = "{CFB4A1CD-694E-4E40-B980-C64822B27EF9}_is1"

[package.speller]
name = "Old French"
version = "0.1.0"

[package.grammar]
name = "Old French"
version = "0.1.0"

[package.tts-textproc]
name = "Old French"
version = "0.1.0"

[package.hyphenator]
name = "Old French"
version = "0.1.0"
