template = "https://github.com/giellalt/template-lang-und"
rev_id = 260
template_sha = "2e95e152f66f76c7c7a22b2f9d91adbb75b07d95"

[replacements]
__GLOTTOLOG_ID__ = "oldf1239"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-fro"
__UND2C__ = "fro"
__UNDEFINED__ = "Old French"
__UND__ = "fro"
