template = "https://github.com/giellalt/template-lang-und"
rev_id = 273
template_sha = "9f0fbd0d561cacc624db71c646d1ccc4d51920f6"

[replacements]
__GLOTTOLOG_ID__ = "oldf1239"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-fro"
__UND2C__ = "fro"
__UNDEFINED__ = "Old French"
__UND__ = "fro"
